CREATE TABLE STUDENT
(
    SNO   VARCHAR(50) NOT NULL,
    SNAME VARCHAR(50) NOT NULL,
    SSEX  int         NOT NULL
);
INSERT INTO STUDENT
VALUES ('001', 'KangKang', 1);
INSERT INTO STUDENT
VALUES ('002', 'Mike', 0);
INSERT INTO STUDENT
VALUES ('003', 'Jane', 0);