server:
  servlet:
    context-path: /web

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: root
    password: admin

mybatis:
  mapper-locations:
    - classpath:/mapper/*.xml

